### ISSUE TITLE
 Evaluation failed: TypeError: Cannot read properties of undefined (reading 'queryExist')

### ISSUE THREAD

**Issue by gg3083** [pedroslopez/whatsapp-web.js#1244]

**Comment by makanSukros** [comment]
Please explain whether you are using the legacy version or the multi-device version, and explain the chronology of when the error appeared

**Comment by nielsonjr** [comment]
I am also getting this error when I check if a number is registered. 

Stacktrace:

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'queryExist')
    at __puppeteer_evaluation_script__:2:49
    at ExecutionContext._evaluateInternal (/home/ubuntu/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ExecutionContext.evaluate (/home/ubuntu/whatsapp/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async ClientWrapper.isRegisteredUser (/home/ubuntu/whatsapp/node_modules/whatsapp-web.js/src/Client.js:871:16)

**Comment by gg3083** [comment]
solve this #1242
