### ISSUE TITLE
Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by RyanRyan99** [pedroslopez/whatsapp-web.js#1495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

process stuck while getting chat

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'filter')
    at __puppeteer_evaluation_script__:5:41
    at ExecutionContext._evaluateInternal (D:\Project\WhatsappSessionAccount\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (D:\Project\WhatsappSessionAccount\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async PrivateChat.fetchMessages (D:\Project\WhatsappSessionAccount\node_modules\whatsapp-web.js\src\structures\Chat.js:178:24)
    at async D:\Project\WhatsappSessionAccount\app-multiple-account.js:323:19

### Expected behavior

restart or reboot

### Steps to Reproduce the Bug or Issue

const message = await chat.fetchMessages({limit: 15});

### Browser Type

Google Chrome

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

whatsapp version ^1.16.6

**Comment by MinosIE** [comment]
fixing see https://github.com/pedroslopez/whatsapp-web.js/issues/1492

**Comment by luiscuriel** [comment]
That fix was for the error reading 'map' but it generates this new error reading 'filter'

**Comment by MinosIE** [comment]
@luiscuriel chat list I am fixing too

**Comment by AnonimBella** [comment]
> #1494
> 
> This is a fix for this bug and loadEarlierMsgs bug

I tried this, but just get latest message, how can I get the earlier messages?

**Comment by MinosIE** [comment]
> 

second time I get the earlier messages

**Comment by MinosIE** [comment]
> > #1494
> > This is a fix for this bug and loadEarlierMsgs bug
> 
> I tried this, but just get latest message, how can I get the earlier messages?

for the first time I get latest message, but second time I get the earlier messages
