### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'unsafe')

### ISSUE THREAD

**Issue by jonylim** [pedroslopez/whatsapp-web.js#1777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When sending message using `Client.sendMessage`, I got the following error:

```
Evaluation failed: TypeError: Cannot read properties of undefined (reading 'unsafe')
    at Object.window.WWebJS.sendMessage (__puppeteer_evaluation_script__:36:67)
    at __puppeteer_evaluation_script__:10:45
    at ExecutionContext._evaluateInternal (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async Client.sendMessage (/usr/src/app/node_modules/whatsapp-web.js/src/Client.js:686:28)
```

### Expected behavior

Message should be sent successfully

### Steps to Reproduce the Bug or Issue

Send a message.

### Browser Type

Chromium

### WhatsApp Account Type

WhatsApp Business

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

Docker (node:lts-alpine3.14)
whatsapp-web.js@1.18.2

**Comment by jonylim** [comment]
Hi, I found out that this issue only happen if sending with `quotedMessageId`. If the same message is sent without `quotedMessageId`, it was sent successfully

**Comment by alexandrereyes** [comment]
+1

**Comment by LittleKing205** [comment]
When I call message.reply("content"), it works.
But when I try to add "quotedMessageId" manually to the options, the error occurs.
Even if I copy the reply code one to one, this error occurs.

The problem is, I don't have the message object while sending, so I have to manually set this as an option.

**Comment by kadirbelen** [comment]
Any progress on this issue? I get the same error when I send ``` quotedMessageId ``` as options during message sending phase

**Comment by LittleKing205** [comment]
I got it to run.
Instead of using the message ID, the complete serialized ID must be used.

`client.sendMessage("xxxx@c.us", "Message Text", { quotedMessageId: "true_xxxx@c.us_3EB096F95744A95428B0_out" });`
instead of
`client.sendMessage("xxxx@c.us", "Message Text", { quotedMessageId: "3EB096F95744A95428B0" });`

**Comment by moraescodes** [comment]
I solved this problem by doing chat.fetchMessages, until I found the message I want to reply to

```
const chat = await client.getChatById("xxxx@c.us");

// I recommend increasing the limit gradually until you find the message
await chat.fetchMessages({ limit: 999 });

await client.sendMessage(
  "xxxx@c.us",
  "Message",
  {
      quotedMessageId: quotedMsgId,
  },
);
```

**Comment by NicoNicoNico123** [comment]
> 



> I got it to run. Instead of using the message ID, the complete serialized ID must be used.
> 
> `client.sendMessage("xxxx@c.us", "Message Text", { quotedMessageId: "true_xxxx@c.us_3EB096F95744A95428B0_out" });` instead of `client.sendMessage("xxxx@c.us", "Message Text", { quotedMessageId: "3EB096F95744A95428B0" });`

What's serialized ID? how to find it from library?

**Comment by LittleKing205** [comment]
The ID attribute in the message object is an object that also contains the serialized ID.

`
client.on('message', message => {
	console.log(message.id._serialized);
});
`

**Comment by zvictor** [comment]
As a workaround, one has to first check if the message has been fetched before quoting it.

```ts
  const chat = await client.getChatById(message.from)
  const options: Whatsapp.MessageSendOptions = {}

  const inCache = (await chat.fetchMessages({})).find(
    (m) => m.id._serialized === message.id._serialized
  )

  options.quotedMessageId = inCache && message.id._serialized
  await client.sendMessage(message.from, 'Hello world!', options)
  ```

**Comment by tanmayrajk** [comment]
Any updates on this?? I'm still having this issue even after using serialized ID.

**Comment by tanmayrajk** [comment]
Ok, so after reading the answers from @zvictor and @moraescodes, reading documentation and some tinkering, I've come up with this solution.
```javascript
import { Chat } from "whatsapp-web.js";

// Checks if the a given message (id) is in a given range.
export async function isInLimit(chat: Chat, id: string, limit = Infinity) {
  let result = (await chat.fetchMessages({ limit })).find((m) => m.id._serialized === id);
  return Boolean(result);
}

// Keeps fetching messages until a given message has been found
export async function fetchTillFound(chat: Chat, id: string) {
  // Gets the current loaded messages.
  const fetchAllMsgsInCache = async () => chat.fetchMessages({ limit: Infinity });

  // Is the message in cache?
  let inCache = await isInLimit(chat, id);
  // This number of extra messages to fetch every time.
  const increment = 50;
  // Number of current loaded messages
  let currentMsgsCount = (await fetchAllMsgsInCache()).length

  // The main loop that keeps fetching messages until the message has been found.
  while (inCache === false) {
    // Increase the current messages count by increment
    currentMsgsCount += increment;
    // Sets the inCache with the new limit. When this variable becomes true, the loop will stop.
    inCache = await isInLimit(chat, id, currentMsgsCount);
  }
  // Return the message found.
  return (await fetchAllMsgsInCache()).find(
    (m) => m.id._serialized === id
  );
}
``` 
**NOTE** - I used ```limit: Infinity``` instead of leaving it blank because it's given in the documentation that to load all the messages in cache you need to use Infinity and it also worked for me. When I left it blank, it loaded some arbitrary amount of messages (like 31 or 51).

**Comment by gabazureus** [comment]
I got this same error when I try to use message.reply when the user delete the message.

Any idea how can I solve this? Already try to put the message.reply inside a try-catch but it does not work, and exit the running anyway.

**Comment by gabazureus** [comment]
I got the same error when I try to use message.reply when the user has deleted the source message.

Any idea how I can resolve this? I've already tried to put the message.reply inside a try-catch but it didn't work, and it exited the execution anyway.

**Comment by gabazureus** [comment]
I got this same error when I try to use message.reply when the user has deleted the source message.

` throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'unsafe')
    at Object.window.WWebJS.sendMessage (__puppeteer_evaluation_script__:36:67)
    at __puppeteer_evaluation_script__:10:45`

Any idea how I can resolve this? I've already tried to put the message.reply inside a try-catch but it didn't work, and it exited the execution anyway.

**Comment by gabazureus** [comment]
I got this same error when I try to use message.reply when the user has deleted the source message.

```
 throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'unsafe')
    at Object.window.WWebJS.sendMessage (__puppeteer_evaluation_script__:36:67)
    at __puppeteer_evaluation_script__:10:45
```

Any idea how I can resolve this? I've already tried to put the message.reply inside a try-catch but it didn't work, and it exited the execution anyway.

**Comment by gabazureus** [comment]
@tanmayrajk and the others, you are awesome! thanks!
