### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'canSend')

### ISSUE THREAD

**Issue by tasaddaq-rana** [pedroslopez/whatsapp-web.js#1821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Following error is coming from the last day,
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'canSend')
    at t.canReplyMsg (https://web.whatsapp.com/bootstrap_qr.f232d10a9d2fea971276.js:75:781494)
    at window.WWebJS.sendMessage (__puppeteer_evaluation_script__:36:41)
    at __puppeteer_evaluation_script__:10:45
    at ExecutionContext._evaluateInternal (E:\project\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (E:\projectr\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.sendMessage (E:\project\node_modules\whatsapp-web.js\src\Client.js:686:28)

### Expected behavior

should check if number is registered with whatsapp or not

### Steps to Reproduce the Bug or Issue

1- check number
2- error

### Browser Type

Google Chrome

### WhatsApp Account Type

WhatsApp Business

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

Windows 10
whatsapp-web.js version : latest

**Comment by khanakhun** [comment]
Same getting facing this issue since yesterday !

**Comment by dannysantino** [comment]
Hi, @khanakhun

Have you found a fix? I'm currently facing the same issue.

**Comment by AlejandroArciniegas** [comment]
Hey, facing same issue just trying to run the example

**Comment by AlejandroArciniegas** [comment]
Got it working by adding headless: false 
```
const client = new Client({
  authStrategy: new LocalAuth(),
  puppeteer: { headless: false }
});
```

**Comment by dannysantino** [comment]
@AlejandroArciniegas Still getting the same error. Which version are you running?
