### ISSUE TITLE
Error installing library in latest version (Injected.js:98)

### ISSUE THREAD

**Issue by juniorerivaldo** [pedroslopez/whatsapp-web.js#2089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Já estou utilizando a biblioteca a alguns dias , porem fui instalar em um novo pc e quando dei npm i   logo após fui testar o bot e me deparei com o seguinte erro :

/home/erivaldo/Documentos/Projetos/conectaweb-producao-1/node_modules/whatsapp-web.js/src/util/Injected.js:98
                m.default?.prototype?.proxyName ||
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/erivaldo/Documentos/Projetos/conectaweb-producao-1/node_modules/whatsapp-web.js/src/Client.js:10:36)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

### Expected behavior

As the user expected there to be the normal initialization of the library

### Steps to Reproduce the Bug or Issue

1. Create a new project
2. Install whats-app-web.js
3. write basic library exemple 
4. try to ruim index.js

### Relevant Code

const qrcode = require("qrcode-terminal");
const { Client,  LocalAuth } = require("whatsapp-web.js");

console.log(":: INICIANDO SISTEMA ::");

  const client = new Client({
    authStrategy: new LocalAuth(),
    puppeteer: {
      headless: false,
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-accelerated-2d-canvas",
        "--no-first-run",
        "--no-zygote",
        "--single-process",
        "--disable-gpu",
      ],
    },
  });

  client.initialize();

  client.on("loading_screen", (percent, message) => {
    console.log(":: CARREGANDO WHATSAPP ", percent, "% ::");
  });

  client.on("qr", (qr) => {
    qrcode.generate(qr, { small: true });
  });

  client.on("authenticated", () => {
    console.log(":: WHATSAPP AUTENTICADO COM SUCESSO ::");
  });

  client.on("auth_failure", (msg) => {
    console.log("AUTHENTICATION FAILURE", msg);
  });

  client.on("ready", () => {
    console.log(":: TUDO PRONTO BOT RODANDO :) ::");
  });

  client.on("message", (msg) => {
    console.log(msg);
  });

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

No, I am not using Multi Device

### Environment

windows and linux

**Comment by juniorerivaldo** [comment]
Solved was using the branch with fix buttons I switched to main now it is installing normally.
