### ISSUE TITLE
 Runtime.callFunctionOn timed out

### ISSUE THREAD

**Issue by zvictor** [pedroslopez/whatsapp-web.js#2107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

_This is not a traditional bug report, as I actually want to share a workaround for an error I was facing. Hopefully it will help future users searching for a solution._

The error below is thrown when you use Puppeteer in a version that is too new.
I was using the [official Puppeteer docker image](https://pptr.dev/guides/docker) (tagged `latest`) as base for my whatsapp-web.js application and that might not be the best idea.
Whatsapp-web.js runs Puppeteer 13.7.0, and that seems to be sensitive and conflicts with other puppeteer versions you might have installed.

```haskell
ProtocolError:  Runtime.callFunctionOn timed out.
    at new Callback (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:61:35)
    at CallbackRegistry.create (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:106:26)
    at Connection._rawSend (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:216:26)
    at CDPSessionImpl.send (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:419:78)
    at ExecutionContext._ExecutionContext_evaluate (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:234:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CDPJSHandle.evaluateHandle (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/common/JSHandle.js:65:16)
    at async WaitTask.rerun (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:108:28)

ProtocolError: Waiting for selector `[data-testid="intro-md-beta-logo-dark"], [data-testid="intro-md-beta-logo-light"], [data-asset-intro-image-light="true"], [data-asset-intro-image-dark="true"]` failed: Runtime.callFunctionOn timed out.
    at new Callback (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:61:35)
    at CallbackRegistry.create (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:106:26)
    at Connection._rawSend (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:216:26)
    at CDPSessionImpl.send (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:419:78)
    at ExecutionContext._ExecutionContext_evaluate (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:234:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CDPJSHandle.evaluateHandle (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/common/JSHandle.js:65:16)
    at async WaitTask.rerun (/home/pptruser/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:108:28)
```
    
## The workaround
Reconsider the base image of your Dockerfile. Ideally you would use `FROM ghcr.io/puppeteer/puppeteer:13.7.0`, but that tag does not exist. Ironically, `19.7.5` works fine.

Here is my Dockerfile
```dockerfile
FROM ghcr.io/puppeteer/puppeteer:19.7.5

RUN npm i fluent-ffmpeg @pedroslopez/moduleraid
COPY . .

ENTRYPOINT ["sh", "-c", "node server.mjs"]
```

### Expected behavior

.

### Steps to Reproduce the Bug or Issue

.

### Relevant Code

.

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

.

### Additional context

.

**Comment by alechkos** [comment]
Duplicate of #1454
