### ISSUE TITLE
message.delete() returns Error: undefined (reading 'pendingDeleteForMeCount') | WaWeb v2.2314.7 

### ISSUE THREAD

**Issue by gkp1** [pedroslopez/whatsapp-web.js#2115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

message.delete() was working properly to delete messages for everyone, a few days ago, now whatsapp web probably changed the function and it returns undefined?

```console
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'pendingDeleteForMeCount')
    at Object.p [as current] (https://web.whatsapp.com/main.5040d1c4cee6edb1de7c.js:5:808279)
    at https://web.whatsapp.com/app.777d9ff19d4bf91ee3d5.js:72:336611
    at f.<anonymous> (https://web.whatsapp.com/app.777d9ff19d4bf91ee3d5.js:72:332782)
    at f._triggerEvents (https://web.whatsapp.com/app.777d9ff19d4bf91ee3d5.js:50:441872)
    at f.trigger (https://web.whatsapp.com/app.777d9ff19d4bf91ee3d5.js:50:440381)
    at f.sendDeleteMsgs (https://web.whatsapp.com/app.777d9ff19d4bf91ee3d5.js:72:786673)
    at __puppeteer_evaluation_script__:9:37
    at ExecutionContext._evaluateInternal (C:\Users\Raposa\Desktop\Code\Bot_Stickers\node_modules\puppeteer\src\common\ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Users\Raposa\Desktop\Code\Bot_Stickers\node_modules\puppeteer\src\common\ExecutionContext.ts:140:12)
    at async Message.delete (C:\Users\Raposa\Desktop\Code\Bot_Stickers\node_modules\whatsapp-web.js\src\structures\Message.js:439:9)
[nodemon] app crashed - waiting for file changes before starting...
```

### Expected behavior

Expected the message to be deleted for everyone. It used to work a few days ago, now it's returning undefined error.

### Steps to Reproduce the Bug or Issue

```ts
if (message.body == ".delete") {
    if (message.hasQuotedMsg) {
      let quotedMsg = await message.getQuotedMessage();
      quotedMsg.delete().catch((e) => {
        message.reply(`Erro ao deletar: ${e}`);
        console.log(e);
      });
    }
    return;
  }
```

### Browser Type

Google Chrome

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

OS: Windows 11 + Ubuntu 22.x, both not working message.delete()
Phone OS: Android
whatsapp-web.js version @1.19.5 
WhatsApp Web version [run await client.getWWebVersion()]:
Node.js Version  v19.0.0 + tested with node v16.x both not working message.delete()

### Additional context

.

**Comment by RC047** [comment]
Same here

**Comment by PiyushDuggal-source** [comment]
same here

**Comment by coffemixer** [comment]
Same here

**Comment by Chuen1988** [comment]
Same here.

**Comment by wslsolucoes** [comment]
same here
