### ISSUE TITLE
Error bug when i use code invitecode group whatsapp

### ISSUE THREAD

**Issue by sakha27pot** [pedroslopez/whatsapp-web.js#2256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Error bug when i use code invitecode group whatsapp

### Expected behavior

-

### Steps to Reproduce the Bug or Issue

-

### Relevant Code

```
else if (message.body.startsWith(`${config.prefix}join`)) {
			const inviteCode = message.body.split(' ')[1];
			try {
				await client.acceptInvite(inviteCode);
				message.reply('Joined the group!');
			} catch (e) `{`
				console.log(e);
				message.reply('That invite code seems to be invalid.');
			}
		}
```

Error: Evaluation failed: i
    at ExecutionContext._evaluateInternal (C:\users\root\BOT\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (C:\users\root\BOT\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
    at async Client.acceptInvite (C:\users\root\BOT\node_modules\whatsapp-web.js\src\Client.js:896:21)
    at async Client.<anonymous> (C:\users\root\BOT\index.js:117:5)

### Browser Type

Google Chrome

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

No, I am not using Multi Device

### Environment

OS:  Windows]
Phone OS: [Android]
whatsapp-web.js version [1.19.3]
WhatsApp Web version [run await client.getWWebVersion()]:
Node.js Version [13.14.0]

**Comment by Fannn03** [comment]
i have a same issue

**Comment by Nurse1angeL** [comment]
same issue

**Comment by tuyuribr** [comment]
stale
