### ISSUE TITLE
Error: spawn Unknown system error -86

### ISSUE THREAD

**Issue by ialexsilva** [pedroslopez/whatsapp-web.js#2333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am getting the following error when trying to run npm run start

```
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:757:9)
    at BrowserRunner.start (/Users/alex/Documents/Development/wa-ia/node_modules/whatsapp-web.js/node_modules/puppeteer/src/node/BrowserRunner.ts:89:30)
    at ChromeLauncher.launch (/Users/alex/Documents/Development/wa-ia/node_modules/whatsapp-web.js/node_modules/puppeteer/src/node/Launcher.ts:162:12)
    at PuppeteerNode.launch (/Users/alex/Documents/Development/wa-ia/node_modules/whatsapp-web.js/node_modules/puppeteer/src/node/Puppeteer.ts:155:27)
    at Client.initialize (/Users/alex/Documents/Development/wa-ia/node_modules/whatsapp-web.js/src/Client.js:106:39) {
  errno: -86,
  code: 'Unknown system error -86',
  syscall: 'spawn'
}
```

### Expected behavior

Run with out errors

### Steps to Reproduce the Bug or Issue

N/A

### Browser Type

Google Chrome

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

Node: 18.16.1
OS: Mac OS Ventura
whatsapp-web.js: 1.21.0

**Comment by gulabsagevadiya** [comment]
thanks bro. you saved me. i got same problem and also worked your solution

**Comment by gerardi0** [comment]
I have this problem. Anyone too?
"Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
at puppeteer_evaluation_script:5:95
at ExecutionContext._evaluateInternal (C:\Users\sorteio2\Desktop\BOTWHATS\node_modules\whatsapp-web.js\node_modules\puppeteer\src\common\ExecutionContext.ts:273:13)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ExecutionContext.evaluate (C:\Users\sorteio2\Desktop\BOTWHATS\node_modules\whatsapp-web.js\node_modules\puppeteer\src\common\ExecutionContext.ts:140:12)
at async Client.initialize (C:\Users\sorteio2\Desktop\BOTWHATS\node_modules\whatsapp-web.js\src\Client.js:323:9)"
