### ISSUE TITLE
Trying to remove participants throws an exception

### ISSUE THREAD

**Issue by Pezmc** [pedroslopez/whatsapp-web.js#2533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When removing a user from a group, whatapp-web crashes entirely:

Previous issue: https://github.com/pedroslopez/whatsapp-web.js/issues/1979

```
./node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: Error: expected at least 1 children, but found 0
    at i (https://web.whatsapp.com/app.896b392b51c1b38bc49c.js:5:761706)
    at t.makeRemoveParticipantsRequest (https://web.whatsapp.com/main.1865f1b812c75c8c32ca.js:2:232668)
    at https://web.whatsapp.com/main.1865f1b812c75c8c32ca.js:2:92198
    at Generator.next (<anonymous>)
    at t (https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:2:32250)
    at s (https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:2:32461)
    at https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:2:32520
    at new Promise (<anonymous>)
    at https://web.whatsapp.com/vendor1~app.7f14216f970118f62a35.js:2:32401
    at f (https://web.whatsapp.com/main.1865f1b812c75c8c32ca.js:2:92774)
    at ExecutionContext._evaluateInternal (/Users/pezcuckow/Git/GithubBot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/Users/pezcuckow/Git/GithubBot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async GroupChat.removeParticipants (/Users/pezcuckow/Git/GithubBot/node_modules/whatsapp-web.js/src/structures/GroupChat.js:80:16)
    at async removeUser (file:///Users/pezcuckow/Git/GithubBot/index.js:654:3)
    at async promptToRemoveUser (file:///Users/pezcuckow/Git/GithubBot/index.js:607:3)
    at async removeUsers (file:///Users/pezcuckow/Git/GithubBot/index.js:580:9)
    at async main (file:///Users/pezcuckow/Git/GithubBot/index.js:289:9)

Node.js v18.18.0
```

### Expected behavior

It should remove the users without error, or throw an error message explaining why it cannot.

### Steps to Reproduce the Bug or Issue

State: A user is a member of a community (and several sub groups).
Try to remove the user from the community using `community.removeParticipants`

Example code:

```
const community = await client.getChatById(COMMUNITY_ID)
await community.removeParticipants(["123455@c.us"])
```

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

OS: Mac
Phone OS: iOS
whatsapp-web.js version: Latest (git@github.com:pedroslopez/whatsapp-web.js.git#152f0a64cdffdfb4d638043f537f87b2a6ebc492)
WhatsApp Web version:  2.2340.1
Node.js Version: Node.js v18.18.0

**Comment by tuyuribr** [comment]
stale
