### ISSUE TITLE
Invalid value { fromMe: true } 

### ISSUE THREAD

**Issue by wilsinho8** [pedroslopez/whatsapp-web.js#2546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Randomly this error explodes on the screen and crashes Chrome.
I took the pm2 log where this error appears:

Error: object - [object Object] - Invalid value { fromMe: true } 
    at Object.escape (/home/deploy/whaticket/backend/node_modules/sequelize/lib/sql-string.js:65:11)
    at MySQLQueryGenerator.escape (/home/deploy/whaticket/backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:986:22)
    at MySQLQueryGenerator._whereParseSingleValueObject (/home/deploy/whaticket/backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2556:41)
    at MySQLQueryGenerator.whereItemQuery (/home/deploy/whaticket/backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2274:19)
    at /home/deploy/whaticket/backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2331:21
    at Array.map (<anonymous>)
    at MySQLQueryGenerator._whereBind (/home/deploy/whaticket/backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2329:43)
    at MySQLQueryGenerator.whereItemQuery (/home/deploy/whaticket/backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2264:19)
    at /home/deploy/whaticket/backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2173:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (/home/deploy/whaticket/backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2171:35)
    at MySQLQueryGenerator.getWhereConditions (/home/deploy/whaticket/backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2583:19)
    at MySQLQueryGenerator.selectQuery (/home/deploy/whaticket/backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1315:28)
    at QueryInterface.select (/home/deploy/whaticket/backend/node_modules/sequelize/lib/query-interface.js:1127:27)
    at /home/deploy/whaticket/backend/node_modules/sequelize/lib/model.js:1759:34
    at tryCatcher (/home/deploy/whaticket/backend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/deploy/whaticket/backend/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/deploy/whaticket/backend/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/deploy/whaticket/backend/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/deploy/whaticket/backend/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/deploy/whaticket/backend/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/deploy/whaticket/backend/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/deploy/whaticket/backend/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/home/deploy/whaticket/backend/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21)
    at process.topLevelDomainCallback (node:domain:161:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)

### Expected behavior

is returning an object instead of returning a boolean field

### Steps to Reproduce the Bug or Issue

use the library normally on an average day

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

Node 18 and puppeteer 19
But i did tests on node 14 and puppeteer 13
Both same errors

**Comment by wilsinho8** [comment]
inside the sql-string it tries several types before throwing the error:

function escape(val, timeZone, dialect, format) {
  let prependN = false;
  if (val === undefined || val === null) {
    return 'NULL';
  }
  switch (typeof val) {
    case 'boolean':
    // SQLite doesn't have true/false support. MySQL aliases true/false to 1/0
    // for us. Postgres actually has a boolean type with true/false literals,
    // but sequelize doesn't use it yet.
      if (dialect === 'sqlite' || dialect === 'mssql') {
        return +!!val;
      }
      return (!!val).toString();
    case 'number':
      return val.toString();
    case 'string':
    // In mssql, prepend N to all quoted vals which are originally a string (for
    // unicode compatibility)
      prependN = dialect === 'mssql';
      break;
  }

  if (val instanceof Date) {
    val = dataTypes[dialect].DATE.prototype.stringify(val, { timezone: timeZone });
  }

  if (Buffer.isBuffer(val)) {
    if (dataTypes[dialect].BLOB) {
      return dataTypes[dialect].BLOB.prototype.stringify(val);
    }

    return dataTypes.BLOB.prototype.stringify(val);
  }

  if (Array.isArray(val)) {
    const partialEscape = escVal => escape(escVal, timeZone, dialect, format);
    if (dialect === 'postgres' && !format) {
      return dataTypes.ARRAY.prototype.stringify(val, { escape: partialEscape });
    }
    return arrayToList(val, timeZone, dialect, format);
  }

  if (!val.replace) {
    throw new Error(`${typeof val} - ${val} - Invalid value ${logger.inspect(val)} `);
  }
