### ISSUE TITLE
TypeError: Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by rsotnas** [pedroslopez/whatsapp-web.js#2828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The error happens after I read the qr code 

```
webCache/LocalWebCache.js:36
        const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
                                                                    ^

TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (/home/felipealves/lab/clickservices/click2ChatWhatsApp/src/whatsapp-web.js/src/webCache/LocalWebCache.js:36:69)
    at /home/felipealves/lab/clickservices/click2ChatWhatsApp/src/whatsapp-web.js/src/Client.js:771:36
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Expected behavior

It should run normally

### Steps to Reproduce the Bug or Issue

1. Read the qr code
2. Stop the service
3. Run again.

It should not be needed to read the qr code again, since it is stored. But instead that error happens.

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

WSL

**Comment by DanielAcostaRoa** [comment]
same issue :-1:

**Comment by itsfabioroma** [comment]
Same here. It seems a kind of dependency issue. I managed get my way around by commenting out the LocalAuth and manually logging in again.

**Comment by itsfabioroma** [comment]
Digging a little bit deeper, I figured out that the bug is happening because of changes inside of the indexHtml being passed as arg to the persist function inside /src/LocalWebCache.js.

Apparently, the manifest version is being loaded dynamically inside the data-sjs, therefore the regex wouldn't be able to extract the version properly. We need a better solution for this. Any ideas?
