### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by javierkusse** [pedroslopez/whatsapp-web.js#2850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Him, since yesterday i cannot use the library, i m getting this error:

/usr/src/app/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:34
        const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
                                                                    ^

TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (/usr/src/app/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:34:69)
    at /usr/src/app/node_modules/whatsapp-web.js/src/Client.js:744:36
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Thanks!

### Expected behavior

I expect to complete de client initialization

### Steps to Reproduce the Bug or Issue

It happen on start

### Browser Type

Chromium

### WhatsApp Account Type

WhatsApp Business

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

I m using v1.23.1-alpha.5

**Comment by NissiusRibas** [comment]
I have the same error here.

estou com o mesmo erro aqui.

**Comment by Benornm** [comment]
Im having this issue also

**Comment by cristian-israel-giganet** [comment]
`const wwebVersion = '2.2407.3';

const client = new Client({
    authStrategy: new LocalAuth(), // your authstrategy here
    puppeteer: {
        // puppeteer args here
    },
    webVersionCache: {
        type: 'remote',
        remotePath: `https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/${wwebVersion}.html`,
    },
});`



Usem dessa forma, consegui inicializar

**Comment by cristian-israel-giganet** [comment]
`const wwebVersion = '2.2407.3';

const client = new Client({
    authStrategy: new LocalAuth(), // your authstrategy here
    puppeteer: {
        // puppeteer args here
    },
    webVersionCache: {
        type: 'remote',
        remotePath: `https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/${wwebVersion}.html`,
    },
});`

**Comment by cristian-israel-giganet** [comment]
```javascript
const wwebVersion = '2.2407.3';

const client = new Client({
    authStrategy: new LocalAuth(), // your authstrategy here
    puppeteer: {
        // puppeteer args here
    },
    webVersionCache: {
        type: 'remote',
        remotePath: `https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/${wwebVersion}.html`,
    },
});
```

**Comment by javierkusse** [comment]
Hi, i solved it erasing the browser cache, and restart the qr vinculation.
