### ISSUE TITLE
How can I fix  TypeError: Cannot read properties of null (reading '1'). Issues raised has always been closed without proper fix by the owner. Fix this buddy.

### ISSUE THREAD

**Issue by Akinyosoye-Oluwatobiloba** [pedroslopez/whatsapp-web.js#2861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
                                                                    ^

TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (/Users/abc/Desktop/haba/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:29:69)
    at /Users/abc/Desktop/haba/node_modules/whatsapp-web.js/src/Client.js:744:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.11.1

once the code is run the second time, it always brings this error.

### Expected behavior

It is supposed to still maintain authentication and not break

### Steps to Reproduce the Bug or Issue

once you run the codthe second time  

### Browser Type

Google Chrome

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

No, I am not using Multi Device

### Environment

Mac
Android

### Additional context

Please, fix this before this issue is closed.

**Comment by devagarwal007** [comment]
I am also facing same issue.

**Comment by thiagossnet** [comment]
I'm also with the same issue.

**Comment by MoudiZd** [comment]
This issue is related to this : 
https://github.com/pedroslopez/whatsapp-web.js/pull/2789

And it seems that this not planned in current time to be solved and released

But you can check opened and closed pull requests that suggest some workarounds, like this one:

https://github.com/pedroslopez/whatsapp-web.js/pull/2827

**Comment by MoudiZd** [comment]
Read more about the new web whatsapp update issues and workarounds here :

https://github.com/pedroslopez/whatsapp-web.js/issues/2856

**Comment by MoudiZd** [comment]
See this :

https://discord.com/channels/698610475432411196/698610475931271249/1224646302609047552

**Comment by rohankm** [comment]
facing same issue

**Comment by CarlosL99** [comment]
Busca ese Js y cambia esa linea por esto
const matchResult = indexHtml.match(/manifest-([\d\\.]+)\.json/);
const version = matchResult ? matchResult[1] : null;

**Comment by Ramon-Wong** [comment]
Previously it worked, but not today.
/home/ramon/projects/proj_001/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:34
        const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
                                                                    ^

TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (/home/ramon/projects/proj_001/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:34:69)
    at /home/ramon/projects/proj_001/node_modules/whatsapp-web.js/src/Client.js:744:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.0.0

**Comment by Ramon-Wong** [comment]
> Read more about the new web whatsapp update issues and workarounds here :
> 
> #2856

okay...thanks for the headsup 
So yeahh, this is kinda expected

**Comment by Ramon-Wong** [comment]
seems like there's a work around to this.
https://github.com/pedroslopez/whatsapp-web.js/pull/2827

**Comment by guilhermesferreira** [comment]
Resolvi com: 

webVersionCache: {
        type: 'remote',
        remotePath: 'https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2412.54.html',
    },
