### ISSUE TITLE
TypeError: Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by hussam-aldarwish** [pedroslopez/whatsapp-web.js#2885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm getting this TypeError when initializing the whatsapp client.

```
TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34:69)
    at node_modules\whatsapp-web.js\src\Client.js:771:36
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Expected behavior

It worked when I tried to skip local caching by directly return like the follwing
```js
    async persist(indexHtml) {
         return;
       }
```
But whiout local cache file stored in /.wwebjs_cache

### Steps to Reproduce the Bug or Issue

I already have another bot working propely, but whenever the client restarted for any reason you will face this error.

### Relevant Code

https://github.com/pedroslopez/whatsapp-web.js/blob/79f0563ae283b4ac3bf40c5e71aba28d78d16557/src/webCache/LocalWebCache.js#L34

### Browser Type

Google Chrome

### WhatsApp Account Type

WhatsApp Business

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

* OS: tried on windows 10, ubuntu 22.04.4 LTS
* whatsapp-web.js version 1.23.1-alpha.5
* WhatsApp Web version: unable to run `await client.getWWebVersion()`
* Node.js Version: tried on v20.11.1 and v16.20.2

**Comment by ichiopro** [comment]
same with me. please help to fix it, thanks

**Comment by RudyBJ** [comment]
Estou com o mesmo problema, será que é devido a alguma atualização?

**Comment by OmarAttia** [comment]
same here

**Comment by codebugged** [comment]
@hussam-aldarwish Sir, can you please expedite this ?
We are facing challenges at client's end

**Comment by moradiyavipul** [comment]
TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (A:\whatsapp\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34:69)
    at A:\whatsapp\node_modules\whatsapp-web.js\src\Client.js:759:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by jdic** [comment]
#2789 
@alechkos 

Just take the corresponding raw version from GitHub, here they are: https://github.com/wppconnect-team/wa-version/tree/main/html

when you already have it, (example: https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2402.5-beta.html), in the launch arguments you should put it like this:

```ts
const client: Client = new Client({
  webVersionCache: 
  {
    remotePath: 'URL PATH HERE',
    type: 'remote' 
  } 
})
```

**Comment by gaurangDhameliya** [comment]
> #2789 @alechkos
> 
> Just take the corresponding raw version from GitHub, here they are: https://github.com/wppconnect-team/wa-version/tree/main/html
> 
> when you already have it, (example: https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2402.5-beta.html), in the launch arguments you should put it like this:
> 
> ```ts
> const client: Client = new Client({
>   webVersionCache: 
>   {
>     remotePath: 'URL PATH HERE',
>     type: 'remote' 
>   } 
> })
> ```

Can you please tell me that which url i need to add in remotePath, And how can I get it?

**Comment by jdic** [comment]
In this link are the wweb version lists, choose the one that corresponds with your version of whatsapp-web.js, you can try with [2.2402.5-beta.html](https://github.com/wppconnect-team/wa-version/blob/main/html/2.2402.5-beta.html), click on that file inside the given github repository list and click where it says raw, now copy the actual URL of the page and paste it in remoteAuth, it should work.

![image](https://github.com/pedroslopez/whatsapp-web.js/assets/125221081/f3a4432a-e335-41c3-8233-e14546783436)

something like this:
```js
const client = new Client({
  webVersionCache: 
  {
    remotePath: 'https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2402.5-beta.html',
    type: 'remote' 
  } 
})
```

> > #2789 @alechkos
> > Just take the corresponding raw version from GitHub, here they are: https://github.com/wppconnect-team/wa-version/tree/main/html
> > when you already have it, (example: https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2402.5-beta.html), in the launch arguments you should put it like this:
> > ```ts
> > const client: Client = new Client({
> >   webVersionCache: 
> >   {
> >     remotePath: 'URL PATH HERE',
> >     type: 'remote' 
> >   } 
> > })
> > ```
> 
> Can you please tell me that which url i need to add in remotePath, And how can I get it?
