### ISSUE TITLE
Connection is stuck - "Synchronization" on Mobile device, "Loading" on whatsapp web screenshot

### ISSUE THREAD

**Issue by Eonus** [pedroslopez/whatsapp-web.js#2888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I started to see this issue from yesterday. The problem is that after scanning QR code, whatsapp web stucks in "Loading" state, and mobile application shows "Synchronization"

### Expected behavior

As a user, I expected to receive `authenditicated` event after scanning the QR code

### Steps to Reproduce the Bug or Issue

1. Set up project
2. Start account
3. Scan the QR code
4. Receive an error

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

OS Ubuntu
Phone OS iOS
whatsapp-web.js version https://github.com/pedroslopez/whatsapp-web.js/tree/webpack-exodus

### Additional context

Problem relates to https://github.com/pedroslopez/whatsapp-web.js/pull/2816

**Comment by TemaSM** [comment]
We had a similar problem.

**We solved it this way:**
1) Installed a VPN on the smartphone, for example, Cloudflare WARP (https://warp.plus/keWnd)
2) Log out of WhatsApp on the smartphone
3) Cleared the cache and data of the WhatsApp app on Android/iOS
4) Reboot smartphone
5) Opened and enabled Cloudflare WARP on the smartphone, confirmed the creation of a VPN profile in Android/iOS
6) Opened WhatsApp smartphone and log in to WhatsApp account
7) Initiated the process of linking the WhatsApp account to the session 
`whatsapp-web.js` via QR code
8) The session successfully started and synchronization completed
Done!

Most likely the problem was due to a DNS issue on the network infrastructure side of WhatsApp/Meta, or there was a connectivity issue.

**Comment by budi-fdln** [comment]
i have same issue with this error
Unhandled rejection:  {} 
 Promise {
  <rejected> Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
      at __puppeteer_evaluation_script__:5:95
      at ExecutionContext._evaluateInternal (D:\CHATBOT\RS\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async ExecutionContext.evaluate (D:\CHATBOT\RS\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16)
      at async Client.initialize (D:\CHATBOT\RS\node_modules\whatsapp-web.js\src\Client.js:323:9)
}
Unhandled rejection:  {} 
 Promise {
  <rejected> TypeError: Cannot read properties of null (reading '1')
      at LocalWebCache.persist (D:\CHATBOT\RS\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34:69)
      at D:\CHATBOT\RS\node_modules\whatsapp-web.js\src\Client.js:744:36
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
}

**Comment by desenvolvimento02jocc** [comment]
> i have same issue with this error Unhandled rejection: {} Promise { Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default') at **puppeteer_evaluation_script**:5:95 at ExecutionContext._evaluateInternal (D:\CHATBOT\RS\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async ExecutionContext.evaluate (D:\CHATBOT\RS\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16) at async Client.initialize (D:\CHATBOT\RS\node_modules\whatsapp-web.js\src\Client.js:323:9) } Unhandled rejection: {} Promise { TypeError: Cannot read properties of null (reading '1') at LocalWebCache.persist (D:\CHATBOT\RS\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34:69) at D:\CHATBOT\RS\node_modules\whatsapp-web.js\src\Client.js:744:36 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) }

same here, waiting for a fix, it alternates between this error and 
`(node:30) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')`

**Comment by chumarrento** [comment]
> i have same issue with this error Unhandled rejection: {} Promise { Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default') at **puppeteer_evaluation_script**:5:95 at ExecutionContext._evaluateInternal (D:\CHATBOT\RS\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async ExecutionContext.evaluate (D:\CHATBOT\RS\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16) at async Client.initialize (D:\CHATBOT\RS\node_modules\whatsapp-web.js\src\Client.js:323:9) } Unhandled rejection: {} Promise { TypeError: Cannot read properties of null (reading '1') at LocalWebCache.persist (D:\CHATBOT\RS\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34:69) at D:\CHATBOT\RS\node_modules\whatsapp-web.js\src\Client.js:744:36 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) }

Same here, sometimes this error occurs too 

`TypeError: Cannot read properties of null (reading '1')  at LocalWebCache.persist (whatsapp-web.js/src/webCache/LocalWebCache.js:33:69)`

**Comment by SergioZhidkov** [comment]
> i have same issue with this error Unhandled rejection: {} Promise { Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default') at **puppeteer_evaluation_script**:5:95 at ExecutionContext._evaluateInternal (D:\CHATBOT\RS\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221:19) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async ExecutionContext.evaluate (D:\CHATBOT\RS\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:110:16) at async Client.initialize (D:\CHATBOT\RS\node_modules\whatsapp-web.js\src\Client.js:323:9) } Unhandled rejection: {} Promise { TypeError: Cannot read properties of null (reading '1') at LocalWebCache.persist (D:\CHATBOT\RS\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34:69) at D:\CHATBOT\RS\node_modules\whatsapp-web.js\src\Client.js:744:36 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) }

We have the same problem. And we have no idea how to fix it...

Also today we have some problems with parsing manifest.json - persist method in LocalWebCache.js nowadays has no profit anymore. If ypou inspect web.whatsapp.com - there is no info about manifest version anymore

**Comment by Eonus** [comment]
Guys please dont mix issues, 
`Cannot read properties of null (reading '1') ` and `Cannot read properties of undefined (reading 'default')` are other issues, not related to this. Please follow discussion here https://github.com/pedroslopez/whatsapp-web.js/issues/2789 and check this PR https://github.com/pedroslopez/whatsapp-web.js/pull/2816

**Comment by Eonus** [comment]
Seems like error happens on version `2.3000.1012539641`

**Comment by Eonus** [comment]
To prevent advices like "use cached version", it does not help here becasue whatsapp anyway change version to this `2.3000.1012539641`
