### ISSUE TITLE
Error fetching version 2.2407.3 from remote FetchError: request to https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2407.3.html failed, reason: getaddrinfo ENOENT raw.githubusercontent.com

### ISSUE THREAD

**Issue by jin-hua-z** [pedroslopez/whatsapp-web.js#2930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Error fetching version 2.2407.3 from remote FetchError: request to https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2407.3.html failed, reason: getaddrinfo ENOENT raw.githubusercontent.com

### Expected behavior

Error fetching version 2.2407.3 from remote FetchError: request to https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2407.3.html failed, reason: getaddrinfo ENOENT raw.githubusercontent.com

### Steps to Reproduce the Bug or Issue

在中国访问 

### Relevant Code

 const wwebVersion = '2.2407.3';
    try {
        client = new Client({
            // authStrategy: new LocalAuth({
            //   clientId: i,
            //   dataPath: app.getPath("userData")
            // }),
            authStrategy: new NoAuth(),
            takeoverTimeoutMs: 5000,
            puppeteer: {
                executablePath: chromiumPath,
                args: chromiumArgs,
            },
            webVersion:wwebVersion,
            webVersionCache: {
                type: 'remote',
                remotePath: `https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/${wwebVersion}.html`,
            },
        });

### Browser Type

Google Chrome

### WhatsApp Account Type

WhatsApp Business

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

windows
Whatsapp-web.js 1.23

### Additional context

Error fetching version 2.2407.3 from remote FetchError: request to https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2407.3.html failed, reason: getaddrinfo ENOENT raw.githubusercontent.com
    at ClientRequest.eval (webpack:///./node_modules/whatsapp-web.js/node_modules/node-fetch/lib/index.mjs?:1507:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  type: 'system',
  errno: 'ENOENT',
  code: 'ENOENT'
}

**Comment by YonatanZviLevy** [comment]
I also had the same problem
Downloading the straw completely and using the branch https://github.com/pedroslopez/whatsapp-web.js/tree/webpack-exodus
solves the problem
