### ISSUE TITLE
Getting error on LocalWebCache.js:34 - version Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by tgmarinho** [pedroslopez/whatsapp-web.js#2954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

getting the error: 
```

~/D/whatsapp-web.js on main ◦ node example.js  15:19:24
/Users/tgmarinho/Developer/whatsapp-web.js/src/webCache/LocalWebCache.js:34
        const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
                                                                    ^

TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (/Users/tgmarinho/Developer/whatsapp-web.js/src/webCache/LocalWebCache.js:34:69)
    at /Users/tgmarinho/Developer/whatsapp-web.js/src/Client.js:771:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Expected behavior

?

### Steps to Reproduce the Bug or Issue

npm start

### Relevant Code

```
/Users/tgmarinho/Developer/whatsapp-web.js/src/webCache/LocalWebCache.js:34
        const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
                                                                    ^

TypeError: Cannot read properties of null (reading '1')
```

### Browser Type

Google Chrome

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

No, I am not using Multi Device

### Environment

Darwin Thiagos-MacBook-Pro.local 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:43 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6000 arm64

Node -v 
v20.10.0

lib version:
v1.23.0

### Additional context

...

**Comment by tgmarinho** [comment]
same issue people are getting here: https://github.com/askrella/whatsapp-chatgpt/issues/336
