### ISSUE TITLE
LocalWebCache

### ISSUE THREAD

**Issue by muhammadaskar** [pedroslopez/whatsapp-web.js#2979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I get error message when i start my project:

/app-prod/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:34
        const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
                                                                    ^

TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (/app-prod/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:34:69)
    at /app-prod/node_modules/whatsapp-web.js/src/Client.js:744:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Expected behavior

I expect succes when i run my project using package whatsapp-web.js

### Steps to Reproduce the Bug or Issue

1. Do npm start

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

OS: Mac and Linux
Phone OS: Android
whatsapp-web.js version 1.23.0
Node.js Version 21.6.2

**Comment by MrJmpl3** [comment]
Try this: https://github.com/pedroslopez/whatsapp-web.js/issues/2789#issuecomment-1992260938

**Comment by PrashantPatil10178** [comment]
I faced a Similar Issue. /app-prod/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:34:69
You can Locate This Directory.
const version = indexHtml.match(/manifest-([\d\\.]+)\.json/)[1];
Just remove [1] from the Code It should Work Fine.
