### ISSUE TITLE
Message.downloadMedia() is throwing "Error: Evaluation failed: Object"

### ISSUE THREAD

**Issue by stefanfuchs** [pedroslopez/whatsapp-web.js#298]
### Bug description
When I call message.downloadMedia(), for some messages (not all of them) puppeteer throws an error. In this specific case, it is an Image message.
I found out that for my specific case, this image was not in my phone anymore. Whatsapp web (in the browser) shows the following message when I try to open it: "Photo Unavailable. Can't view this photo because it's no longer on your phone."
I believe that instead of throwing an error like the one bellow, simply a null value should be returned. Or maybe an error with a better error message should be thrown.

Bellow the full error message. Note: I just replaced all occurences of my local project folder path with `<project_folder>`

```
(node:7836) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Object
    at ExecutionContext._evaluateInternal (<project_folder>\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\ExecutionContext.js:102:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at ExecutionContext.evaluate (<project_folder>\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\ExecutionContext.js:33:16)
    at Message.downloadMedia (<project_folder>\node_modules\whatsapp-web.js\src\structures\Message.js:202:24)
  -- ASYNC --
    at ExecutionContext.<anonymous> (<project_folder>\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\helper.js:94:19)
    at DOMWorld.evaluate (<project_folder>\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\DOMWorld.js:89:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
  -- ASYNC --
    at Frame.<anonymous> (<project_folder>\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\helper.js:94:19)
    at Page.evaluate (<project_folder>\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\Page.js:612:14)
    at Page.<anonymous> (<project_folder>\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\helper.js:95:27)
    at Message.downloadMedia (<project_folder>\node_modules\whatsapp-web.js\src\structures\Message.js:202:50)
    at ChatBotWhatsappServer.<anonymous> (<project_folder>\src\chatbot\channels\whatsapp\ChatBotWhatsappServer.ts:449:47)
    at Generator.next (<anonymous>)
    at fulfilled (<project_folder>\node_modules\tslib\tslib.js:112:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:7836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

### Reproduction steps
1. Fetch messages from a chat
2. For all the messages that have `hasMedia === true`, call downloadMedia()

### Expected behavior 
A null value should be returned for a file that does not exist in the phone, or a better error message should be thrown.

### Environment (please complete the following information):
**WhatsApp**
 - Account type: Business
 - Device OS: Android
 - WhatsApp Web version: 2.2031.4

**Library**
 - Browser: Chromium
 - NodeJS version (`node -v`): v12.14.1
 - npm or yarn version (`npm -v`): v6.14.4
 - whatsapp-web.js version: v1.7.0

### Related issues
#283

**Comment by Leoalmeida95** [comment]
I also have this problem when I try to download the media a few conversations.

According to official documentation, you shouldn't assume that the download will be successful, as explained in the following link:
https://waguide.pedroslopez.me/features/handling-attachments

However, even though I know this and try to deal with all possible ways, I can not prevent this error from occurring sometimes.

It would be nice if it were possible to avoid unless the exception was thrown. Instead of throwing this exception, even when the media has the property 'hasMedia', it would return a null instead of throwing an exception.

**Comment by stefanfuchs** [comment]
I though of a solution which would be wrapping the Message.downloadMedia() evaluate call in a try-catch, and return null in case of error.
The disadvantage would be that those errors could become invisible and more dificult to debug.

I have tried checking for null props in this PR: #304 , but the error message still persists when trying to download (some) media.
Maybe we should try to find the underlying cause.

**Comment by stefanfuchs** [comment]
I was testing and I found that the error occurs in Message.js downloadMedia(), in the evaluate function.
Doing a try catch and console.log(e), this error popped up:

```js
{
message: "hmac check failure", 
name: "MediaEncryptionError",
stack: "MediaEncryptionError: hmac check failure
    at t.n (https://web.whatsapp.com/app.3edd7478de09f0c4750f.js:1:1062722)
    at new t (https://web.whatsapp.com/app.3edd7478de09f0c4750f.js:1:351109)
    at https://web.whatsapp.com/app2.bd99e00dba1790b9096f.js:2:1319121
    at K (https://web.whatsapp.com/app.3edd7478de09f0c4750f.js:1:1032864)
    at MutationObserver.W (https://web.whatsapp.com/app.3edd7478de09f0c4750f.js:1:1032445)"
}
```

This line was throwing the error:
`const decrypted = await window.Store.CryptoLib.decryptE2EMedia(msg.type, buffer, msg.mediaKey, msg.mimetype);`

I believe that because the media data was not on the phone (or corrupted), the media could not be decrypted correctly.
BTW, I checked the buffer in this test, but it was NOT empty.

So a solution, I believe, would be to wrap the whole thing in a try catch and return null in case of error.

What do you guys think?

**Comment by parthibd** [comment]
There is a possibility that even though the message exists but the media doesn't, hence the exception. The most ideal solution would be to wrap this in a try catch. I never faced this issue, probably because all my media files exist but I believe in your case it doesn't. I'll suggest upgrading the library to the latest version and trying it out. Do let me know if try catch fixed your problem.

**Comment by stefanfuchs** [comment]
@parthibd I am using try catch externally, like this:

```js
let media = null
try {
  media = message.downloadMedia()
} catch (e) {
  console.log(e)
}
```

However this doesn't feel ideal to me. I believe a try-catch should be done internally in the `downloadMedia` method, and `null` should be returned if the media could not be downloaded.

**Comment by parthibd** [comment]
You are more than welcome to make a pull request if you want any specific changes that you deem useful.

**Comment by best-tech** [comment]
this is reproduced with the old messages, the new ones work. how do I download old media?

**Comment by PurpShell** [comment]
.
