### ISSUE TITLE
E: forward a received message

### ISSUE THREAD

**Issue by glbatistabh** [pedroslopez/whatsapp-web.js#728]
### Bug description

When forwarding a received message to another WhatsApp number it is giving the message **"Error: Evaluation failed: TypeError: Cannot read property 'forwardMessages' of undefined"**

> (node:121495) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'forwardMessages' of undefined
>     at __puppeteer_evaluation_script__:5:31
>     at ExecutionContext._evaluateInternal (/home/baptist/devel/whats/whats-api/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at async ExecutionContext.evaluate (/home/baptista/devel/whats/whats-api/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
>     at async Message.forward (/home/baptista/devel/whats/whats-api/node_modules/whatsapp-web.js/src/structures/Message.js:226:9)
>     at async Client.<anonymous> (/home/baptista/devel/whats/whats-api/core/server/config-events.js:160:5)

### Reproduction steps
1. create an observer "client.on('message' )'"
```
 client.on('message', async (message) => {
    let forwardTo = '55319239XXXX@c.us'; //part of the number was purposely hidden
    await message.forward(forwardTo);
  });
```
2. send a message from another WhatsApp to WhatsApp connected to whatsapp-web.js;

### Expected behavior
Expected the message to be forwarded to the other whastApp number (numberTo)

### Environment (please complete the following information):
**Whatsapp**
 - Account type: Standard:
 - Device OS: Android:
 - WhatsApp Web version: 2.2123.8

**Library**
 - Browser : chromium:
 - NodeJS: v14.17.2
 - npm or yarn version: 6.14.13
 - whatsapp-web.js version: "^1.12.6"

**PrintScreen**
Code:
![image](https://user-images.githubusercontent.com/8257020/124767591-5398ef80-df0e-11eb-9f23-69c5b6d83bb1.png)

Console:
![image](https://user-images.githubusercontent.com/8257020/124766974-c6559b00-df0d-11eb-8bb1-6a9e26169e38.png)

**Comment by glbatistabh** [comment]
Nobody? `message.forward(chat)` works for you"?

**Comment by NowDev** [comment]
Just figured out after some testing that this problem only happens if you never talked with the contact that you will forward the message before.
I don't think that this is a issue to be adressed by wa-web.js but should be documented.

**Comment by glbatistabh** [comment]
I don't understand why an error occurs. On "whatsapp web" I can forward a message to a contact I've never chatted with without problems.
